version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
          applies-to: version-updates
          patterns:
              - '*'
          dependency-type: development
      production-dependencies:
          applies-to: version-updates
          patterns:
              - '*'
          dependency-type: production
    cooldown:
      default-days: 7
      include:
          - '*'
      exclude:
          - react

  - package-ecosystem: pip
    directory: /services/console-ui
    schedule:
      interval: daily
    groups:
      dev-dependencies:
          applies-to: version-updates
          patterns:
              - '*'
          dependency-type: development
      production-dependencies:
          applies-to: version-updates
          patterns:
              - '*'
          dependency-type: production
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 5
      include:
          - '*'
      exclude:
          - react

  - package-ecosystem: pip
    directory: /services/contrastdatacollector
    schedule:
      interval: daily
    groups:
      dev-dependencies:
          applies-to: version-updates
          patterns:
              - '*'
          dependency-type: development
      production-dependencies:
          applies-to: version-updates
          patterns:
              - '*'
          dependency-type: production
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 5
      include:
          - '*'
      exclude:
          - react

  - package-ecosystem: pip
    directory: /services/docservice
    schedule:
      interval: daily
    groups:
      dev-dependencies:
          applies-to: version-updates
          patterns:
              - '*'
          dependency-type: development
      production-dependencies:
          applies-to: version-updates
          patterns:
              - '*'
          dependency-type: production
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 5
      include:
          - '*'
      exclude:
          - react

  - package-ecosystem: npm
    directory: /services/labelservice
    schedule:
      interval: daily
    groups:
      dev-dependencies:
          applies-to: version-updates
          patterns:
              - '*'
          dependency-type: development
      production-dependencies:
          applies-to: version-updates
          patterns:
              - '*'
          dependency-type: production
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 5
      include:
          - '*'
      exclude:
          - react

  - package-ecosystem: pip
    directory: /services/webhookservice
    schedule:
      interval: daily
    groups:
      dev-dependencies:
          applies-to: version-updates
          patterns:
              - '*'
          dependency-type: development
      production-dependencies:
          applies-to: version-updates
          patterns:
              - '*'
          dependency-type: production
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 5
      include:
          - '*'
      exclude:
          - react

  - package-ecosystem: maven
    directory: /services/dataservice
    schedule:
      interval: daily
    groups:
      dev-dependencies:
          applies-to: version-updates
          patterns:
              - '*'
          dependency-type: development
      production-dependencies:
          applies-to: version-updates
          patterns:
              - '*'
          dependency-type: production
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 5
      include:
          - '*'
      exclude:
          - react

  - package-ecosystem: maven
    directory: /services/frontgateservice
    schedule:
      interval: daily
    groups:
      dev-dependencies:
          applies-to: version-updates
          patterns:
              - '*'
          dependency-type: development
      production-dependencies:
          applies-to: version-updates
          patterns:
              - '*'
          dependency-type: production
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 5
      include:
          - '*'
      exclude:
          - react
